### ISSUE TITLE
Return false if orientation cannot be determined

### ISSUE THREAD

**Issue by monsieurchico** [JellyBellyDev/ImageOrientationFix#1]
https://github.com/JellyBellyDev/ImageOrientationFix/blob/a2352ffe4150c0aac17d9d17d08d60bad9d0d14a/src/ImageOrientationFix.php#L59

// do nothing if orientation cannot be determined
if (null === $this->image->getOrientation()) { 
    return false; 
}

**Comment by JellyBellyDev** [comment]
Thanks @monsieurchico!
closed by https://github.com/JellyBellyDev/ImageOrientationFix/pull/2
