### ISSUE TITLE
Exit on exception

### ISSUE THREAD

**Issue by monsieurchico** [JellyBellyDev/ImageOrientationFix#4]
https://github.com/JellyBellyDev/ImageOrientationFix/blob/738aa9f428f2bdf8b7ab03b77426d9f7a6a3be89/src/ImageOrientationFix.php#L40

You have have to remove your try catch in order to let the exception been thrown

**Comment by peter279k** [comment]
It should remove `exit` and let exception been thrown or output.

@JellyBellyDev, any news here :)?

**Comment by JellyBellyDev** [comment]
@peter279k would you like to do a PR?

**Comment by JellyBellyDev** [comment]
Fixed here: https://github.com/JellyBellyDev/ImageOrientationFix/pull/10
