### ISSUE TITLE
The current PHP version requirements

### ISSUE THREAD

**Issue by peter279k** [JellyBellyDev/ImageOrientationFix#7]
https://github.com/JellyBellyDev/ImageOrientationFix/blob/579ee7dc1b88cbe67d4720ee2cafda9cadadae1e/composer.json#L23

It seems that the package requires `php-5.2` version at least, but from `php-5.2` to `php-5.5` are not tested on Travis CI build.

IMHO, it should drop these `php-5.x` versions because they're outdated and old.

@JellyBellyDev, do you have any idea about this?

**Comment by JellyBellyDev** [comment]
@peter279k yes, we could increase in majors and go to write code for `php >= 7.1`. 
What do you think about it?

**Comment by peter279k** [comment]
@JellyBellyDev, let the package minimum PHP requirement is `php-7.1` version should be fine.

I will create PR to work on this :).

**Comment by JellyBellyDev** [comment]
@peter279k thank you so much!

**Comment by JellyBellyDev** [comment]
@peter279k what do you think about pass to psr4?

**Comment by peter279k** [comment]
Hi @JellyBellyDev, thanks for your reply.

I think it will be good to change into `PSR-4` autoloading :).

**Comment by JellyBellyDev** [comment]
@peter279k  
I created a branch `1.x` == `master` (for the future)

and i created the branch `2.x-dev` for the our improvement. Once the progress is complete, we margin everything on the master and tag v2.0.0.

Ok?

**Comment by JellyBellyDev** [comment]
Closed by https://github.com/JellyBellyDev/ImageOrientationFix/pull/10
