### ISSUE TITLE
Docker container build test

### ISSUE THREAD

**Issue by peter279k** [JellyBellyDev/ImageOrientationFix#8]
It seems that this package has the [docker-compose.yml](https://github.com/JellyBellyDev/ImageOrientationFix/blob/master/docker-compose.yml) file.

And I think we should let this Docker build file have the test on CI build.

It can let us make sure development environment container will be worked :).

**Comment by JellyBellyDev** [comment]
@peter279k Totally agree. I entered it precisely for this, some time ago! 😉

**Comment by JellyBellyDev** [comment]
Closed by https://github.com/JellyBellyDev/ImageOrientationFix/pull/10
